export const projects = [
  {
    title: 'Ambientar',
    description: "My final project at UnB. Ambientar is an educational software designed to help in the teaching of students diagnosed with classical autism. It was developed in Android and made for tablets.",
      image: '/images/ambientar.jpg',
      tags: ['Android', 'Java'],
    source: 'https://google.com',
    visit: 'http://www.projetoparticipar.unb.br/autismo/ambientar',
    id: 0,
  },
  {
    title: 'It\'s Pay',
    description: "As a Full Stack developer for It's Pay, I developed new projects for clients, realized maintenance in existing code and created SQL queries to generate reports.",
      image: '/images/its-pay.jpg',
      tags: ['Angular', 'Java', 'Spring', 'PostgreSQL'],
    source: 'https://google.com',
    visit: 'https://itspay.com.br',
    id: 1,
  },
  {
    title: 'Mobile app - Banco do Brasil',
    description:"As an employee from Stefanini, I was assigned to Banco do Brasil to develop maintenance for the bank's mobile app.",
    image: '/images/app-bb.jfif',
    tags: ['Android', 'Java', 'COBOL'],
    source: 'https://google.com',
    visit: 'https://www.bb.com.br/pbb/pagina-inicial/solucoes-digitais/aplicativo-bb#/',
    id: 2,
  },
  {
    title: 'Valor de Bens Rurais - Banco do Brasil',
    description: "In this project I developed a system designed to determine rural real estate value based on GPS positioning and information provided in a form. The system then estimates the value using the parameters provided, generating a pdf report, that can be validated by the bank.",
      image: '/images/valor-bens-rurais.jpg',
      tags: ['Angular', 'NodeJS', 'PostgreSQL', 'Docker'],
    source: 'https://google.com',
    visit: 'https://valordebensrurais.bb.com.br/#/',
    id: 3,
  },
  {
    title: 'Ártemis - Banco do Brasil',
    description: "This project was a development of the bank's new internal communication system, designed to be a social network. In this system, we developed, from scratch, a social network for the bank's employees countrywide, where they had individual user accounts, created group accounts, traded messages, shared posts, likes, and had personalized content in their feed.",
    image: '/images/bb.jpg',
    tags: ['Angular', 'NodeJS', 'MongoDB', 'Redis'],
    source: 'https://google.com',
    visit: 'https://www.bb.com.br/pbb/pagina-inicial/voce#/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2009, text: 'Started Computer Science at UnB - Universidade de Brasília', },
  { year: 2012, text: 'Project published at SBGames - Game developed in C++', },
  { year: 2013, text: 'Studied at University of Adelaide - Australia', },
  { year: 2016, text: 'Graduated from UnB', },
  { year: 2018, text: 'Full Stack developer at It\'s Pay', },
  { year: 2019, text: 'Full Stack developer at Stefanini, working for Banco do Brasil', },
  { year: 2022, text: 'Freelance jobs', },
];